repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the specific version you want
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.6.0  # Use the version of Black you want
    hooks:
    -   id: black
-   repo: https://github.com/myint/autoflake
    rev: v2.2.1  # Use the desired version
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--recursive']
